language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run test

deploy:
    provider: npm
    api_key: $NPM_TOKEN
    email: $NPM_EMAIL
    skip_cleanup: true    
    on:
      branch: master 

notifications:
  email:
    on_failure: change