language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build:prod

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN

notifications:
  email:
    on_failure: change